# Change these first
owner: Raymond-Weng # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Blog
    url: https://rwc.dpdns.org/
  - name: rwlink.us.kg
    url: https://rwlink.us.kg/
    method: GET

assignees:
 - Raymond-Weng

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rwc.dpdns.org
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/87399369
  name: Raymond's services monitor
  introTitle: "Monitor for all services made by **Raymond Weng**."
  introMessage: Feel free to give my projects a try.
  navbar:
    - title: Status
      href: /
    - title: My Blog
      href: https://rwc.dpdns.org
    - title: GitHub
      href: https://github.com/$OWNER/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
